services:
  # Whisper Server Backend (GPU version)
  whisper-server:
    build:
      context: .
      dockerfile: Dockerfile.whisper
    container_name: whisper-server
    ports:
      - "8081:8081"
    volumes:
      # Mount models directory to persist downloaded models
      - whisper-models:/app/models
      # Mount audio files for processing (optional)
      - ./audio:/app/audio:ro
    environment:
      - CUDA_VISIBLE_DEVICES=0  # Use first GPU, comment out for CPU-only
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - whisper-network
    profiles:
      - gpu

  # Whisper Server Backend (CPU version)
  whisper-server-cpu:
    build:
      context: .
      dockerfile: Dockerfile.whisper-cpu
    container_name: whisper-server-cpu
    ports:
      - "8081:8081"
    volumes:
      - whisper-models:/app/models
      - ./audio:/app/audio:ro
    environment:
      - WHISPER_NO_GPU=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - whisper-network
    profiles:
      - cpu

  # Web Frontend
  web-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: whisper-frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - whisper-network

  # Optional: Reverse Proxy (Nginx)
  reverse-proxy:
    image: nginx:alpine
    container_name: whisper-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # Add SSL certificates here if needed
      # - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - whisper-server
      - web-frontend
    restart: unless-stopped
    profiles:
      - production
    networks:
      - whisper-network

volumes:
  whisper-models:
    driver: local

networks:
  whisper-network:
    driver: bridge

# Alternative CPU-only version (comment out GPU sections above)
# services:
#   whisper-server-cpu:
#     build:
#       context: .
#       dockerfile: Dockerfile.whisper
#       args:
#         - BUILD_TYPE=cpu
#     container_name: whisper-server-cpu
#     ports:
#       - "8081:8081"
#     volumes:
#       - whisper-models:/app/models
#     environment:
#       - WHISPER_NO_GPU=1
#     restart: unless-stopped